image: ros:noetic-ros-core
variables:
  # If package name is "ros-noetic-actionlib" it becomes "actionlib" (remove the prefix)
  ROS_PACKAGES_TO_INSTALL: "actionlib" # Here the package is useless, it is just for demonstration

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git >/dev/null
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

# noetic
noetic catkin_make:
  stage: build
  script:
    - catkin_make

noetic catkin build:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color

# melodic
melodic catkin_make:
  image: ros:melodic-ros-core
  stage: build
  script:
    - catkin_make

melodic catkin build:
  image: ros:melodic-ros-core
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
